### ISSUE TITLE
AMD Linting

### ISSUE THREAD

**Issue by WoMspace** [Strum355/mcshader-lsp#38]
I tried to build the latest commit asking for AMD debug output but I'm not familiar with rust (or c for that matter) compiling so I couldn't. If you can drop a binary I can get the output here and now

**Comment by Strum355** [comment]
https://github.com/Strum355/mcshader-lsp/suites/5728403922/artifacts/190321067 this link should do the job (I hope)

**Comment by WoMspace** [comment]
I need a windows x86 binary for my AMD machine, the mac has the apple silicon GPU

**Comment by Strum355** [comment]
https://github.com/Strum355/mcshader-lsp/suites/5728403922/artifacts/190666979 my bad, thought you were on the M1

**Comment by WoMspace** [comment]
Now I feel like I'm being stupid. Dropping in to replace the existing binary on the extension version 0.9.5 generates a bunch of errors that don't have anything to do with glsl.

**Comment by Strum355** [comment]
Can you show what they are? Did you unzip the file?

**Comment by WoMspace** [comment]
I did unzip it. Here are the errors.
```Mar 22 00:26:24.423 INFO OpenGL device, renderer: AMD Radeon RX 5700 XT, version: 4.6.14800 Compatibility Profile/Debug Context 22.3.1 30.0.15002.1004, vendor: ATI Technologies Inc.
Mar 22 00:26:24.426 INFO starting server..., trace: aadcf24c
Mar 22 00:26:24.426 INFO generating graph for current root, root: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader, trace: aadcf24c
Mar 22 00:26:24.801 INFO finished building project include graph, trace: aadcf24c
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `log_level`", line: 0, column: 0)', src\main.rs:562:124
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Error, task queue channel closed without explicit agent shutdown: RecvError', C:\Users\runneradmin\.cargo\git\checkouts\rustdt-json_rpc-d710a3f3543c1508\e2394e9\src\output_agent.rs:172:17
[Error - 00:26:24] Connection to server got closed. Server will not be restarted.
[Error - 00:26:24] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:3880:25)
	at Object.dispose (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:8058:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:10292:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:11701:15)
	at closeHandler (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:10279:18)
	at CallbackList.invoke (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:1999:39)
	at Emitter.fire (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:2058:36)
	at closeHandler (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:3216:26)
	at CallbackList.invoke (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:1999:39)
	at Emitter.fire (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:2058:36)
	at StreamMessageReader.fireClose (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:2182:27)
	at Socket.<anonymous> (c:\Users\Alex\.vscode\extensions\strum355.vscode-mc-shader-0.9.5\client\out\extension.js:2222:46)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```
It did the thing where an extension crashes 5 times in 3 minutes and stops trying to start it.

**Comment by Strum355** [comment]
Yup good catch, forgot you'll need https://github.com/Strum355/mcshader-lsp/suites/5745071432/artifacts/190594209 too, install like so:
![image](https://user-images.githubusercontent.com/18282288/159785970-69f953a7-6499-4312-b4d7-2712bbd2dd88.png)

**Comment by WoMspace** [comment]
This doesn't look like quite what you want, but it didn't crash!
```
Mar 23 21:11:23.359 INFO compilation errors reported, errors: `Fragment shader failed to compile with the following errors:\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#397) Illegal escape sequence\nERROR: 0:16: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#397) Illegal escape sequence\nERROR: 0:51: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#397) Illegal escape sequence\nERROR: 0:52: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#397) Illegal escape sequence\nERROR: 0:1: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#397) Illegal escape sequence\nERROR: 0:53: error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#397) Illegal escape sequence\nERROR: 0:? : error(#74) Syntax error: unexpected tokens following #line\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#397) Illegal escape sequence\nERROR: 0:54: error(#74) Syntax error: unexpected tokens following #line\nERROR: error(#273) 290 compilation errors.  No code generated\n\n`, trace: 1c4c4547
```

**Comment by WoMspace** [comment]
I got bamboozled ignore this comment

**Comment by Strum355** [comment]
Work on this is delayed because of development on windows raising issues I didnt have on Linux 🙂🙂🙂

**Comment by WoMspace** [comment]
That's fine I'm just an idiot and thought I hadn't sent the log yet lmao

**Comment by Strum355** [comment]
No idea if this will work, but lets give it a go https://github.com/Strum355/mcshader-lsp/suites/5913817574/artifacts/201864945 (may be completely broken, havent tested)

**Comment by WoMspace** [comment]
This is like... close! So as far as I understand I should be getting a long list of errors from AMD, but I'm not.
However, if I write invalid code it does find the error and tell me what's going on in the Output for the language server, but notably it doesn't show it in the Problems tab.
Also, hovering over an #include link and then pressing control as if to follow it throws an error:
```
[Error - 01:04:57] Request textDocument/definition failed.
  Message: error building parser context: file:///c%3A/Users/Alex/AppData/Roaming/.minecraft/shaderpacks/Epoch-Shader/shaders/composite15.fsh
  Code: 42069 
```
For context, the file I'm viewing is the listed composite15.fsh, and the file I'm hovering over the #include for is in a lib folder

All in all, it looks like this is VERY nearly working as it should!

_p.s. Nice Error Code_

**Comment by Strum355** [comment]
>  if I write invalid code it does find the error and tell me what's going on in the Output for the language server, but notably it doesn't show it in the Problems tab.
Can you drop the Output panel output for this? Ideally from a fresh start so theres less noise

>  Also, hovering over an #include link and then pressing control as if to follow it throws an error
Yea can ignore this for now, just some stuff Im playing around with

**Comment by WoMspace** [comment]
No Errors in code:
```
Apr 05 13:42:18.384 INFO OpenGL device, renderer: AMD Radeon RX 5700 XT, version: 4.6.14800 Compatibility Profile/Debug Context 22.3.2 30.0.15019.1005, vendor: ATI Technologies Inc.
Apr 05 13:42:18.386 INFO starting server..., trace: 1daf7483
Apr 05 13:42:18.386 INFO generating graph for current root, root: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader, trace: 1daf7483
Apr 05 13:42:18.991 INFO finished building project include graph, trace: 1daf7483
Apr 05 13:42:18.991 INFO got updated configuration, config: {"logLevel":"info","skipBootstrap":true}, trace: 8654fadb
Apr 05 13:42:18.992 INFO top-level file ancestors found, ancestors: [], uri: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader\shaders\composite15.fsh, trace: 534ce293
Apr 05 13:42:18.994 INFO compilation reported no errors, tree_root: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader\shaders\composite15.fsh, trace: 534ce293
```
With error in code:
```
Apr 05 13:43:39.678 INFO OpenGL device, renderer: AMD Radeon RX 5700 XT, version: 4.6.14800 Compatibility Profile/Debug Context 22.3.2 30.0.15019.1005, vendor: ATI Technologies Inc.
Apr 05 13:43:39.680 INFO starting server..., trace: 2fdc6c4f
Apr 05 13:43:39.680 INFO generating graph for current root, root: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader, trace: 2fdc6c4f
Apr 05 13:43:40.057 INFO finished building project include graph, trace: 2fdc6c4f
Apr 05 13:43:40.057 INFO got updated configuration, config: {"logLevel":"info","skipBootstrap":true}, trace: 3a4d33b7
Apr 05 13:43:40.057 INFO top-level file ancestors found, ancestors: [], uri: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader\shaders\composite15.fsh, trace: 18ac4054
Apr 05 13:43:40.060 INFO compilation errors reported, tree_root: c:\Users\Alex\AppData\Roaming\.minecraft\shaderpacks\Epoch-Shader\shaders\composite15.fsh, errors: `Fragment shader failed to compile with the following errors:\nWARNING: 2:80: warning(#288) Divide by zero error during constant folding\nERROR: 0:53: error(#132) Syntax error: "float" parse error\nERROR: error(#273) 1 compilation errors.  No code generated\n\n`, trace: 18ac4054
```

**Comment by Strum355** [comment]
Ah yea seems to just be a regex thing, making me wonder now if different AMD drivers have different output format...

**Comment by WoMspace** [comment]
oh that would SUCK 😅

**Comment by Strum355** [comment]
https://github.com/Strum355/mcshader-lsp/suites/6059239688/artifacts/209115274 @WoMspace

**Comment by Strum355** [comment]
And it works, closing this now. Need to adjust the offset by 1, then release

![image](https://user-images.githubusercontent.com/18282288/162586022-4ce313b4-7a6d-4402-b81e-8a8e8f8aed94.png)
